---
# tasks file for ansible-role-template

- name: Detect template VM
  set_fact:
    template_vm: true
  when: ansible_hostname.find("template-debian-") != -1

- include_tasks: check-and-update.yml
  when: template_vm|bool
